# Generated by Django 4.2.7 on 2025-03-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0002_alter_analisis_options_alter_enlace_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='texto_alternativo',
            new_name='alt',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='formato',
        ),
        migrations.RenameField(
            model_name='hallazgo',
            old_name='mensaje',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='tipo',
            field=models.CharField(choices=[('error', 'Error'), ('warning', 'Advertencia'), ('info', 'Información'), ('recomendacion', 'Recomendación')], max_length=20, verbose_name='Tipo'),
        ),
    ]
