# Generated by Django 4.2.7 on 2025-03-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0003_auto_20250319_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlace',
            name='tipo',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='externo', max_length=20),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
