# Generated by Django manually due to sandbox environment issues
# Intended to add crawl_scope, num_pages_solicitadas, and tecnologia_sitio to Analisis model

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0005_analisis_analisis_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='crawl_scope',
            field=models.CharField(choices=[('single_url', 'Single URL'), ('multiple_pages', 'Multiple Pages')], default='single_url', max_length=20, verbose_name='Crawl Scope'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='num_pages_solicitadas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Pages Requested'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='tecnologia_sitio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Website Technology'),
        ),
    ]
